osx_image: xcode8.2
language: objective-c

before_install:
  - brew update || brew update
  - brew outdated xctool || brew upgrade xctool

script:
- xcodebuild -scheme BinarySearch -destination 'id=22FA2149-1241-469C-BF6D-462D3837DB72'
- xcodebuild test -scheme BinarySearch -destination 'id=22FA2149-1241-469C-BF6D-462D3837DB72'
