osx_image: xcode7.1
language: objective-c

before_install:
  - brew update || brew update
  - brew outdated xctool || brew upgrade xctool

script:
- xctool -scheme BinarySearch -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
- xctool test -scheme BinarySearch -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
