osx_image: xcode8.2
language: objective-c

before_install:
  - brew update || brew update
  - brew outdated xctool || brew upgrade xctool

script:
- xcodebuild -scheme BinarySearch -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.2'
- xcodebuild test -scheme BinarySearch -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.2'
