osx_image: xcode8.2
language: objective-c

before_install:
  - brew update || brew update
  - brew outdated xctool || brew upgrade xctool

script:
- xcodebuild -scheme BinarySearch -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
- xcodebuild test -scheme BinarySearch -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
